---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'release'

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: make version
        run: |
          make version .env.docker
      - run: make ci-report
      - run: make build-docker-image
      - run: make build-in-docker
      - run: make validate-in-docker
      - name: upload packages
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/**/*
      - name: make release-in-docker
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "release" ]]; then
            export CI_BRANCH=${GITHUB_REF#refs/heads/}
            export PACKAGECLOUD_REPOSITORY=dokku/dokku
            rm .env.docker
            make .env.docker release-in-docker release-packagecloud-in-docker
          fi
